import "@/styles/globals.css";

import { type Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import ReactLenis from "lenis/react";
import { AuthProvider } from "@/context/auth";
import Sidebar from "@/components/root/sidebar";
import Footer from "@/components/root/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const hk = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hk",
});

const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.ttf",
  variable: "--font-satoshi",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${hk.variable} ${satoshi.variable} antialiased`}
    >
      <ReactLenis root>
        <AuthProvider>
          <body>
            <Sidebar />
            {children}
            <Footer />
          </body>
        </AuthProvider>
      </ReactLenis>
    </html>
  );
}
