import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import ReactLenis from "lenis/react";
import Sidebar from "@/components/common/sidebar";

const hk = Hanken_Grotesk({
  variable: "--font-hk",
  subsets: ["latin"],
  display: "swap",
})

const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.ttf",
  variable: "--font-satoshi",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <ReactLenis root>
      <body
        className={`${hk.variable} ${satoshi.variable} antialiased`}
      >
      <Sidebar />
        {children}
      </body>
    </ReactLenis>
    </html>
  );
}
